### ISSUE TITLE
Deploy Shared Folder Permissions fails with Invalid Response object: Value of property Data must be an object

### ISSUE THREAD

**Issue by gilcesarf** [trustep/io.trustep.aws.cloudformation.custom-resources#8]
Customer reports error when deploying the following permission with message: "Invalid Response object: Value of property Data must be an object". (actual values masked for security)

```yaml
...
  pruebaPermissionDsOrdenesTrabajo:
    Type: Custom::QuicksightPermissions
    Properties:
      ServiceToken:
        'Fn::ImportValue':
          'Fn::Sub': '${customPermissionStackName}-QuicksightPermissions-Lambda-Arn'
      FolderId: a1b2234c-67de-890a-bc12-d34e56789a01
      Permissions:
        - Principals:
            - arn:aws:quicksight:us-east-1:XXXXXXXXXXXX:user/default/QuickSight-Autor-Role/my.user@foo.bar.com
          Actions:
            - quicksight:DescribeFolder
...
```

The error at the log group of the lambda that implements the custom resource:

```bash
INIT_START Runtime Version: nodejs:20.v18	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:b8c2913782bf648152634d2f893a4c02250aec5884edb545f64c2bd7268d214e
START RequestId: request-uuid Version: $LATEST
2024-03-20T13:47:35.696Z	request-uuid	DEBUG	EVENT RECEIVED:
 
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:StackSet-cfn-custom-resource-QuicksightPermissions-random",
    "ResponseURL": "https://cloudformation-custom-resource-response-useast1.s3.amazonaws.com/.....",
    "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/dataset-dev/cfn-stack-uuid",
    "RequestId": "cfn-request-uuid",
    "LogicalResourceId": "pruebaPermissionDsOrdenesTrabajo",
    "ResourceType": "Custom::QuicksightPermissions",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:StackSet-cfn-custom-resource-QuicksightPermissions-random",
        "Permissions": [
            {
                "Principals": [
                    "arn:aws:quicksight:us-east-1:XXXXXXXXXXXX:user/default/QuickSight-Autor-Role/my.user@foo.bar.com"
                ],
                "Actions": [
                    "quicksight:DescribeFolder"
                ]
            }
        ],
        "FolderId": "a1b2234c-67de-890a-bc12-d34e56789a01"
    }
}

2024-03-20T13:47:37.249Z	request-uuid	ERROR	Error name:  AccessDeniedException
2024-03-20T13:47:37.249Z	request-uuid	ERROR	Error message:  User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/StackSet-cfn-custom-resou-QuicksightPermissionsRole-random/StackSet-cfn-custom-resource-QuicksightPermissions-random is not authorized to perform: quicksight:DescribeFolderPermissions on resource: arn:aws:quicksight:us-east-1:XXXXXXXXXXXX:folder/a1b2234c-67de-890a-bc12-d34e56789a01 because no identity-based policy allows the quicksight:DescribeFolderPermissions action
2024-03-20T13:47:37.308Z	request-uuid	ERROR	Stack trace:  AccessDeniedException: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/StackSet-cfn-custom-resou-QuicksightPermissionsRole-random/StackSet-cfn-custom-resource-QuicksightPermissions-random is not authorized to perform: quicksight:DescribeFolderPermissions on resource: arn:aws:quicksight:us-east-1:XXXXXXXXXXXX:folder/a1b2234c-67de-890a-bc12-d34e56789a01 because no identity-based policy allows the quicksight:DescribeFolderPermissions action
    at de_AccessDeniedExceptionRes (/var/task/node_modules/@aws-sdk/client-quicksight/dist-cjs/index.js:8982:21)
    at de_CommandError (/var/task/node_modules/@aws-sdk/client-quicksight/dist-cjs/index.js:8909:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /var/task/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async Object.DescribeFolderPermissions [as describe] (file:///var/task/index.mjs:262:20)
    at async getActualPermissions (file:///var/task/index.mjs:483:10)
    at async Runtime.handler (file:///var/task/index.mjs:816:29)
2024-03-20T13:47:37.486Z	request-uuid	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "200",
    "stack": [
        "Error: 200",
        "    at Object.intoError (file:///var/runtime/index.mjs:46:16)",
        "    at Object.textErrorLogger [as logError] (file:///var/runtime/index.mjs:684:56)",
        "    at postError (file:///var/runtime/index.mjs:801:27)",
        "    at done (file:///var/runtime/index.mjs:833:11)",
        "    at Object.done (file:///var/runtime/index.mjs:872:20)",
        "    at IncomingMessage.<anonymous> (file:///var/task/index.mjs:527:19)",
        "    at IncomingMessage.emit (node:events:530:35)",
        "    at endReadableNT (node:internal/streams/readable:1696:12)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
    ]
}

END RequestId: request-uuid
```

**Comment by gilcesarf** [comment]
The problem occurs because the lambda execution role that runs the custom resource does not have permissions to describe quicksight permissions.
